<?php

// Can be used by any webpage to implement a basic error handling.

if (isset($_GET['error'])) {
	$error = $_GET['error'];
	// It's already an error message generated by formr and it already in html.
	if (substr($error, 0, 1) === "<") {
		echo $_GET['error'];
	} else {
		// It's an error message from a controller. We need to add HTML to it.
		echo '<div class="alert alert-danger"><p>'.$error.'</p></div>';
	}
}